version: '3.8'
services:
  dbms:
    image: postgres:12.9
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT} 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
  wait:
    image: jwilder/dockerize
    environment:
      TZ: ${OS_TIMEZONE}
    command: tail -f /dev/null
  web:
    image: nginx:1.21.0-alpine
    volumes:
      - ${WEB_MOUNT_DIR}:/usr/share/nginx/html
  smtp:
    image: mailhog/mailhog:v1.0.1
    environment:
      TZ: ${OS_TIMEZONE}